#!/bin/sh

# easyexplorer package made by fw867
# package maintained at http://www.koolshare.cn

PKGNAME="easyexplorer"
PKGPATH="/var/packages/${PKGNAME}"

BINPKG=`ls -l ${PKGPATH}/target | awk -F "-> " '{print $2}'`

BINPATH="bin"
BINFILE="easyexplorer"
BINLOG="easy-explorer.log"

BINSTART=${BINPKG}/${BINPATH}/${BINFILE}

case $1 in
	start)
		echo "Starting easyexplorer ..."
		${BINSTART} >/dev/null 2>&1 &
		exit 0
	;;
	stop)
		echo "Stopping easyexplorer ..."
		killall ${BINFILE}
		exit 0
	;;
	status)
		pidof ${BINFILE} > /dev/null
		if [ $? -ne 0 ]; then
			echo "Status: easyexplorer is not running"
			exit 1
		fi
		echo "Status: easyexplorer is running"
		exit 0
	;;
    log)
        echo ${BINPKG}/${BINPATH}/${BINLOG}
    ;;
esac
